# Generated by Django 3.2.24 on 2024-03-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
